# shellcheck shell=bash
# Generated by scripts/generate_bash_completion.py. Do not edit manually.

_FONTSHOW_COMMANDS="create-catalog dump-fonts parse-inventory preflight validate-inventory"
_FONTSHOW_GLOBAL_OPTIONS="--help --version -V -h"

_FONTSHOW_OPTIONS_CREATE_CATALOG="--appendix-descriptions --catalog-detail --help --indexed-navigation --inventory --language --list-test-fonts --number --output --quiet --script --sort-by --test --test-font --verbose --version -A -D -I -L -S -T -V -h -i -l -n -o -q -s -t -v"
_FONTSHOW_PATH_OPTIONS_CREATE_CATALOG="--inventory --output -i -o"
_FONTSHOW_POSITIONAL_PATH_CREATE_CATALOG=0

_FONTSHOW_OPTIONS_DUMP_FONTS="--cache-dir --help --include-fc-charset --loadability-jobs --no-cache --output --paths --quiet --verbose --version -V -c -h -i -l -n -o -q -v"
_FONTSHOW_PATH_OPTIONS_DUMP_FONTS="--cache-dir --output --paths -c -o"
_FONTSHOW_POSITIONAL_PATH_DUMP_FONTS=0

_FONTSHOW_OPTIONS_PARSE_INVENTORY="--help --infer-level --list-missing-language-coverage --loadability-jobs --output --quiet --show-all-missing-language-coverage --strict-bcp47 --validate-inventory --verbose --version -I -L -S -V -h -i -l -o -q -s -v"
_FONTSHOW_PATH_OPTIONS_PARSE_INVENTORY="--output -o"
_FONTSHOW_POSITIONAL_PATH_PARSE_INVENTORY=1

_FONTSHOW_OPTIONS_PREFLIGHT="--help --output --quiet --verbose --version -V -h -o -q -v"
_FONTSHOW_PATH_OPTIONS_PREFLIGHT="--output -o"
_FONTSHOW_POSITIONAL_PATH_PREFLIGHT=0

_FONTSHOW_OPTIONS_VALIDATE_INVENTORY="--help --quiet --verbose --version -V -h -q -v"
_FONTSHOW_PATH_OPTIONS_VALIDATE_INVENTORY=""
_FONTSHOW_POSITIONAL_PATH_VALIDATE_INVENTORY=1

_fontshow_contains_word() {
    local needle="$1"
    shift
    local item
    for item in "$@"; do
        if [[ "$item" == "$needle" ]]; then
            return 0
        fi
    done
    return 1
}

_fontshow_complete_files() {
    COMPREPLY=( $(compgen -f -- "$1") )
}

_fontshow_complete() {
    local cur prev command command_key options path_options positional_paths
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    command="${COMP_WORDS[1]}"

    if (( COMP_CWORD == 1 )); then
        COMPREPLY=( $(compgen -W "${_FONTSHOW_COMMANDS} ${_FONTSHOW_GLOBAL_OPTIONS}" -- "$cur") )
        return 0
    fi

    if [[ -z "$command" ]]; then
        return 0
    fi

    command_key="${command^^}"
    command_key="${command_key//-/_}"
    eval "options=\${_FONTSHOW_OPTIONS_${command_key}}"
    eval "path_options=\${_FONTSHOW_PATH_OPTIONS_${command_key}}"
    eval "positional_paths=\${_FONTSHOW_POSITIONAL_PATH_${command_key}}"

    if _fontshow_contains_word "$prev" $path_options; then
        _fontshow_complete_files "$cur"
        return 0
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "${options} ${_FONTSHOW_GLOBAL_OPTIONS}" -- "$cur") )
        return 0
    fi

    if [[ "$positional_paths" == "1" ]]; then
        _fontshow_complete_files "$cur"
        return 0
    fi

    COMPREPLY=()
}

complete -F _fontshow_complete fontshow
