[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "fontshow"
dynamic = ["version"]
description = "Fontshow utilities"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Marco Coppola" }]

[tool.setuptools_scm]
tag_regex = "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"
version_scheme = "post-release"
local_scheme = "no-local-version"

[project.optional-dependencies]
dev = ["black", "ruff", "pre-commit"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
