"""
Verify deterministic pipeline output.

This module tests that the Fontshow catalog generation pipeline
produces deterministic outputs when executed multiple times with the
same inputs.

Responsibilities
----------------
- Ensure repeated catalog generation yields identical results.
- Verify that serialized catalog data remains stable.
- Detect unintended nondeterministic behavior in the pipeline.

Design principles
-----------------
Deterministic tests compare serialized artifacts generated by the
catalog pipeline so regressions caused by ordering or environment
differences can be detected early.

Architectural role
------------------
This module belongs to the **test infrastructure layer** and verifies
deterministic behavior of the Fontshow catalog generation pipeline.
"""

import argparse
import json
import os
from pathlib import Path

from fontshow.cli.create_catalog import (
    build_parser,
    run_create_catalog,
)
from tests.helpers import minimal_inventory_v12


def _run(tmp_path, inventory):
    """
    Run create-catalog in an isolated temporary directory and return the TEX bytes.

    Parameters
    ----------
    tmp_path : pathlib.Path
        Temporary directory used for the inventory input and generated output.
    inventory : dict
        Inventory payload written to disk and passed to the CLI.

    Returns
    -------
    bytes
        Raw bytes of the generated ``.tex`` artifact.
    """
    tmp_path.mkdir(parents=True, exist_ok=True)

    inv = tmp_path / "inv.json"
    inv.write_text(json.dumps(inventory), encoding="utf-8")

    parser = argparse.ArgumentParser()
    build_parser(parser)

    args = parser.parse_args(
        [
            "--inventory",
            str(inv),
            "--quiet",
        ]
    )

    old_cwd = Path.cwd()
    try:
        os.chdir(tmp_path)
        rc = run_create_catalog(args)
        assert rc == 0

        tex_files = list(tmp_path.glob("*.tex"))
        assert len(tex_files) == 1
        return tex_files[0].read_bytes()
    finally:
        os.chdir(old_cwd)


def test_deterministic_catalog_output(tmp_path):
    """
    Verify that repeated catalog generation with identical input is byte-stable.

    Parameters
    ----------
    tmp_path : pathlib.Path
        Base temporary directory fixture used to create two isolated runs.

    Returns
    -------
    None
    """
    inventory = minimal_inventory_v12()

    font_a = inventory["fonts"][0]
    font_a["family"] = "Alpha"
    font_a["full_name"] = "Alpha Regular"
    font_a["postscript_name"] = "Alpha-Regular"
    font_a["unique_font_id"] = "alpha-regular-1.0"
    font_a["coverage"]["languages"] = ["en"]

    font_b = dict(font_a)
    font_b["path"] = "/fake/beta.ttf"
    font_b["family"] = "Beta"
    font_b["full_name"] = "Beta Regular"
    font_b["postscript_name"] = "Beta-Regular"
    font_b["unique_font_id"] = "beta-regular-1.0"
    font_b["coverage"] = dict(font_a["coverage"])
    font_b["coverage"]["languages"] = ["fr"]

    inventory["fonts"] = [font_a, font_b]

    out1 = _run(tmp_path / "run1", inventory)
    out2 = _run(tmp_path / "run2", inventory)

    assert out1 == out2
