name: TODO / Improvement
description: General TODO extracted from documentation
title: "todo: "
labels: ["todo"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: Describe the task to be done
    validations:
      required: true
