"""
Fontshow – parse_font_inventory.py
=================================

Parse and enrich a ``font_inventory.json`` produced by ``dump_fonts.py`` by
applying deterministic inference of writing scripts and language candidates.

Design principles
-----------------
- **Cross-platform**: works only on JSON data, never touches font files.
- **Deterministic**: same input → same output.
- **Non-destructive**: declared metadata is never overwritten.
- **Configurable**: inference aggressiveness selectable from CLI.

Default inference level: ``medium``.
"""

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from fontshow import __version__
from fontshow.cli_utils import (
    add_common_arguments,
    log_err,
    log_info,
    log_ok,
    log_warn,
    set_cli_mode,
)
from fontshow.diagnostics.inventory_warnings import (
    _collect_language_warnings,
    _format_font_identity,
)
from fontshow.global_constants import SCHEMA_VERSION
from fontshow.inventory.io import _validate_fonts_container
from fontshow.inventory.metadata_processing import (
    _infer_and_attach_metadata,
    _process_charset,
    _process_language_metadata,
)
from fontshow.inventory.specimens import _specimen_generate_for_font
from fontshow.inventory.validation import _apply_schema_validation, validate_inventory
from fontshow.json_boundary import normalize_loaded_enums
from fontshow.json_format import dumps_pretty
from fontshow.logging_utils import log, log_trace_cat
from fontshow.platform_metadata import collect_platform_metadata
from fontshow.schema_validation import _validate_inventory_schema_strict

if TYPE_CHECKING:
    from fontshow.types import FontRef

# ============================================================
# Set up logger
# ============================================================
logger = logging.getLogger("fontshow")


# ============================================================
# REFACTORED MAIN FUNCTION
# ============================================================


def parse_inventory(
    data: dict[str, Any],
    level: str,
    *,
    strict_bcp47: bool = False,
) -> dict[str, Any]:
    """
    Parse and enrich a font inventory structure.

    Refactored version:
    - reduced complexity
    - separated concerns
    - behavior unchanged
    """

    _apply_schema_validation(data)

    logger.info(
        "font inventory parsing started",
        extra={
            "schema_version": data.get("schema_version"),
            "fonts_count": len(data.get("fonts", [])),
        },
    )

    for font in data.get("fonts", []):
        identity = font.get("identity", {})
        font_path = font.get("path")
        family = identity.get("family")
        style = identity.get("style")

        logger.debug(
            "font entry parsing started",
            extra={"font_path": font_path, "family": family, "style": style},
        )

        coverage: dict[str, Any] = font.get("coverage", {}) or {}

        _process_charset(font, coverage, font_path)

        _infer_and_attach_metadata(
            font,
            coverage,
            level=level,
            font_path=font_path,
        )

        _process_language_metadata(
            font,
            coverage,
            strict_bcp47=strict_bcp47,
        )

        _specimen_generate_for_font(font, coverage, font_path)

    metadata = data.setdefault("metadata", {})
    metadata["schema_version"] = SCHEMA_VERSION
    metadata["inference_level"] = level
    metadata.setdefault("input_inventory_tool", "parse_font_inventory")
    metadata.setdefault("input_inventory_tool_version", __version__)

    logger.info(
        "font inventory parsing completed",
        extra={"fonts_processed": len(data.get("fonts", []))},
    )

    return data


# ============================================================
# CLI
# ============================================================


def build_parser(parser: argparse.ArgumentParser) -> None:
    """
    Register parse-inventory CLI arguments on an existing parser.
    """
    parser.description = (
        "Parse and enrich a Fontshow font_inventory.json with deterministic inference."
    )
    parser.formatter_class = argparse.ArgumentDefaultsHelpFormatter
    parser.add_argument(
        "input",
        type=Path,
        nargs="?",
        default=Path("font_inventory.json"),
        help="Input font_inventory.json generated by dump_fonts.py",
    )
    parser.add_argument(
        "-i",
        "--infer-level",
        choices=["conservative", "medium", "aggressive"],
        default="medium",
        help="Inference aggressiveness level",
    )
    parser.add_argument(
        "-I",
        "--validate-inventory",
        action="store_true",
        help="Validate inventory structure and exit (no output generation)",
    )
    parser.add_argument(
        "-s",
        "--strict-bcp47",
        action="store_true",
        help="Reject non-compliant BCP-47 language tags",
    )
    add_common_arguments(
        parser,
        include_output=True,
        output_default=Path("font_inventory_enriched.json"),
        output_help="Output enriched JSON file",
    )


def register_cli(parser) -> None:
    """
    Register parse-inventory CLI arguments.

    This function is used by the top-level fontshow dispatcher.
    """
    build_parser(parser)
    parser.set_defaults(func=main)


# ============================================================
# Helper: default I/O adapters (test-friendly)
# ============================================================


def _default_read_text(p: Path) -> str:
    """Default file reader used when no injectable I/O is provided."""
    return p.read_text(encoding="utf-8")


def _default_write_text(p: Path, s: str) -> None:
    """Default file writer used when no injectable I/O is provided."""
    p.write_text(s, encoding="utf-8")


# ============================================================
# Helper: verbose warning emitter
# ============================================================


def _emit_verbose_warnings(enriched: dict[str, Any]) -> None:
    """Emit grouped warnings for verbose CLI mode."""

    fonts = enriched.get("fonts", [])
    if not isinstance(fonts, list):
        return

    for idx, font in enumerate(fonts):
        if not isinstance(font, dict):
            continue

        ident = _format_font_identity(font, idx)

        norm, dups, dropped, other = _collect_language_warnings(cast("FontRef", font))

        if norm:
            log_info(f"{ident} normalized_languages: {', '.join(sorted(set(norm)))}")

        if dups:
            log_info(f"{ident} duplicate_languages: {', '.join(sorted(set(dups)))}")

        if dropped:
            log_warn(f"{ident} dropped_languages: {', '.join(sorted(set(dropped)))}")

        for _severity, code, message in other:
            log_warn(f"{ident} {code}: {message}")


# ============================================================
# REFACTORED MAIN RUNNER
# ============================================================


def run_parse_font_inventory(
    args,
    *,
    parse_inventory_fn=parse_inventory,
    validate_inventory_fn=validate_inventory,
    read_text_fn=None,
    write_text_fn=None,
) -> int:
    """
    Internal runner for parse-font-inventory CLI.

    Refactored version:
    - reduced complexity
    - helpers extracted
    - behavior unchanged
    """
    strict_bcp47 = bool(getattr(args, "strict_bcp47", False))

    log_trace_cat(
        log,
        "flow",
        "parse-inventory runner started",
        extra={
            "input": str(args.input),
            "output": str(args.output),
            "infer_level": getattr(args, "infer_level", None),
            "strict_bcp47": strict_bcp47,
            "validate_only": bool(getattr(args, "validate_inventory", False)),
        },
    )

    read_text_fn = read_text_fn or _default_read_text
    write_text_fn = write_text_fn or _default_write_text

    input_path = args.input
    if not input_path.exists():
        log_err(f"input file not found: {input_path}")
        log_err("Hint: run dump_fonts.py first to generate the inventory.")
        return 1

    logger.debug("inference level enabled", extra={"infer_level": args.infer_level})

    data: dict[str, Any] = json.loads(read_text_fn(input_path))
    normalize_loaded_enums(data)
    log_trace_cat(
        log,
        "io",
        "inventory JSON loaded",
        extra={
            "fonts": len(data.get("fonts", [])),
            "schema_version": data.get("metadata", {}).get("schema_version"),
        },
    )

    metadata = data.get("metadata")
    if not isinstance(metadata, dict):
        log_err("invalid inventory: missing or invalid 'metadata' object")
        return 1

    actual_env = metadata.get("run_environment")
    if not isinstance(actual_env, dict):
        log_err("invalid inventory: missing or invalid 'metadata.run_environment'")
        return 1

    expected_env = collect_platform_metadata()
    if actual_env != expected_env:
        log_err(
            "invalid inventory: 'metadata.run_environment' does not match current platform"
        )
        return 1
    try:
        _validate_inventory_schema_strict(data)
    except ValueError as exc:
        log_err(f"schema validation failed: {exc}")
        return 1
    fonts = _validate_fonts_container(data)
    if fonts is None:
        return 1

    if args.validate_inventory:
        log_trace_cat(
            log,
            "flow",
            "validate-only mode",
            extra={
                "fonts": len(data.get("fonts", [])),
            },
        )

        rc = int(validate_inventory_fn(data))

        if rc == 0:
            log_ok(
                "Inventory validation completed (no fatal errors)",
                f"Validation completed for {len(data.get('fonts', []))} font entries",
            )
        else:
            log_info("Inventory validation failed with errors")

        return rc

    enriched = parse_inventory_fn(
        data,
        args.infer_level,
        strict_bcp47=args.strict_bcp47,
    )
    log_trace_cat(
        log,
        "flow",
        "inventory enriched",
        extra={
            "fonts": len(enriched.get("fonts", [])),
            "schema_version": enriched.get("metadata", {}).get("schema_version"),
        },
    )

    try:
        # Validate normalized JSON, not Python object
        normalized_for_validation = json.loads(
            dumps_pretty(enriched, indent=2, ensure_ascii=False)
        )
        _validate_inventory_schema_strict(normalized_for_validation)
    except ValueError as exc:
        log_err(f"schema validation failed (output): {exc}")
        return 1

    write_text_fn(
        args.output,
        dumps_pretty(enriched, indent=2, ensure_ascii=False),
    )
    log_trace_cat(
        log,
        "io",
        "enriched inventory written",
        extra={
            "path": str(args.output),
            "fonts": len(enriched.get("fonts", [])),
        },
    )
    log_trace_cat(
        log,
        "flow",
        "verbose warning emission started",
        extra={
            "fonts": len(enriched.get("fonts", [])),
        },
    )

    _emit_verbose_warnings(enriched)

    log_ok("Done.", f"Inventory written to {args.output}")
    log_trace_cat(
        log,
        "flow",
        "parse-inventory runner completed",
        extra={
            "fonts": len(enriched.get("fonts", [])),
            "output": str(args.output),
        },
    )

    return 0


def _run_parse_inventory(args) -> int:
    """
    Indirection layer for CLI testing.

    This function exists so CLI tests can monkeypatch it
    without touching the core implementation.
    """
    return run_parse_font_inventory(args)


def run(args):
    """
    Public CLI entrypoint (kept stable).
    Thin wrapper around the injectable runner.
    Needed for tests via the top-level dispatcher.
    """
    return main(args)


def main(args) -> int:
    """
    Public CLI entrypoint (kept stable).
    Thin wrapper around the injectable runner.
    """

    set_cli_mode(getattr(args, "quiet", False), getattr(args, "verbose", False))

    from time import perf_counter

    t0 = perf_counter()
    try:
        exit_code = _run_parse_inventory(args)
        log_trace_cat(
            log,
            "perf",
            "inventory parse metrics",
            extra={
                "exit_code": exit_code,
            },
        )
    except TypeError as exc:
        if not getattr(args, "quiet", False):
            log_err(f"parse-inventory failed: {exc}")
        log_trace_cat(
            log,
            "perf",
            "inventory parse metrics",
            extra={
                "exit_code": 2,
                "exception": True,
            },
        )
        exit_code = 2
    finally:
        duration_ms = int((perf_counter() - t0) * 1000)
        log_trace_cat(
            log,
            "perf",
            "parse-inventory timing",
            extra={
                "duration_ms": duration_ms,
                "exit_code": exit_code,
            },
        )

    return exit_code


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="parse-inventory")
    build_parser(parser)
    args = parser.parse_args()
    sys.exit(main(args))
