#!/usr/bin/env python3

import re
from pathlib import Path

DOCS_DIR = Path("docs")
OUTPUT = DOCS_DIR / "cheatsheet.md"

PATTERN = re.compile(
    r"<!-- cheatsheet:start -->(.*?)<!-- cheatsheet:end -->",
    re.DOTALL | re.IGNORECASE,
)

blocks = []

for md_file in sorted(DOCS_DIR.rglob("*.md")):
    text = md_file.read_text(encoding="utf-8")
    matches = PATTERN.findall(text)

    for block in matches:
        blocks.append(block.strip())

header = """# Fontshow – Cheat Sheet

This cheat sheet is **automatically generated** from the project documentation.

Do not edit this file manually.
"""

content = "\n\n---\n\n".join(blocks)

OUTPUT.write_text(
    header + "\n\n" + content + "\n",
    encoding="utf-8",
)

print(f"Generated {OUTPUT} with {len(blocks)} sections")
