#!python
"""
Generate the project cheat sheet.

This maintenance script scans the documentation tree for marked
cheat-sheet fragments and assembles them into a single generated
`docs/cheatsheet.md` file for quick reference.

Responsibilities
----------------
- Discover markdown files under the documentation tree.
- Extract blocks delimited by cheat-sheet markers.
- Write a deterministic aggregated cheat-sheet document.

Design principles
-----------------
Generated documentation must be reproducible and derived only from source
documentation blocks explicitly marked for inclusion. The script performs
a one-way aggregation step and avoids any interpretation beyond marker
extraction and stable ordering.

Architectural role
------------------
This module belongs to the developer tooling layer and provides a
documentation-maintenance utility used during repository upkeep rather
than at Fontshow runtime.
"""

import re
from pathlib import Path

DOCS_DIR = Path("docs")
OUTPUT = DOCS_DIR / "cheatsheet.md"

PATTERN = re.compile(
    r"<!-- cheatsheet:start -->(.*?)<!-- cheatsheet:end -->",
    re.DOTALL | re.IGNORECASE,
)

blocks = []

for md_file in sorted(DOCS_DIR.rglob("*.md")):
    text = md_file.read_text(encoding="utf-8")
    matches = PATTERN.findall(text)

    for block in matches:
        blocks.append(block.strip())

header = """# Fontshow – Cheat Sheet

This cheat sheet is **automatically generated** from the project documentation.

Do not edit this file manually."""

content = "\n\n---\n\n".join(blocks)

OUTPUT.write_text(
    header + "\n\n" + content + "\n",
    encoding="utf-8",
    newline="\n",
)

print(f"Generated {OUTPUT} with {len(blocks)} sections")
