#!/usr/bin/env python3
"""
Inventory jq query helper for Fontshow schema inspection.

Responsibilities
----------------
- Preserve reusable `jq` queries for inspecting Fontshow inventory JSON.
- Expose deterministic query choices through a small command-line wrapper.
- Print interpretation guidance so query results can be read consistently.

Design principles
-----------------
This helper keeps inspection logic outside the production runtime and
stores the exact `jq` filters as durable repository artifacts. The script
is intentionally explicit: each query has a stable name, purpose, filter,
and interpretation note.

Architectural role
------------------
This module belongs to the developer tooling layer. It supports manual
inspection of inventory files generated by `fontshow dump-fonts` without
changing the application itself.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class QuerySpec:
    """
    Immutable metadata for one saved `jq` inventory query.

    Parameters
    ----------
    name : str
        Stable command-line identifier used to select the query.
    summary : str
        Short human-readable description printed in listings.
    query : str
        Exact `jq` program text passed to the `jq` executable.
    interpretation : str
        Plain-text guidance explaining how to read the result.

    Returns
    -------
    None
    """

    name: str
    summary: str
    query: str
    interpretation: str


QUERY_SPECS: tuple[QuerySpec, ...] = (
    QuerySpec(
        name="schema-v1-3",
        summary="Check schema 1.3 metadata/typography/loadability blocks.",
        query=r"""
def nonempty: type == "string" and length > 0;
def nullable_string: . == null or type == "string";
def nullable_bool: . == null or type == "boolean";
def glyph_count_ok: . == null or (type == "number" and floor == . and . >= 1);
def fp_ok: . == null or (type == "string" and length == 64);
def strategy_ok:
  . as $v
  | ["internal","script","cmap","deferred","validated-language-sample","validated-fallback"]
  | index($v) != null;

def metadata_ok:
  .metadata.schema_version == "1.3"
  and (.metadata.validation.lualatex.attempted | type == "boolean")
  and (.metadata.validation.lualatex.engine | nullable_string)
  and (.metadata.validation.lualatex.engine_version | nullable_string)
  and (.metadata.validation.lualatex.luaotfload_version | nullable_string)
  and (.metadata.validation.lualatex.fontspec_version | nullable_string)
  and (.metadata.validation.lualatex.polyglossia_version | nullable_string)
  and (.metadata.validation.lualatex.runtime_fingerprint | fp_ok)
  and (.metadata.validation.lualatex.render_policy_version | nullable_string);

def font_ok:
  (.typography.sample_text.source == "font")
  and (.typography.sample_text.text | type == "string")
  and (.typography.specimen_text | nonempty)
  and (.typography.specimen_strategy | strategy_ok)
  and (.typography.specimen_glyph_count | glyph_count_ok)
  and (.typography.specimen_rejection_reason | nullable_string)
  and (.typography.primary_script | nullable_string)
  and (.typography.script_display_name | nullable_string)
  and (.typography.render_policy.polyglossia_language | nullable_string)
  and (.typography.render_policy.fontspec_opts | nullable_string)
  and (.typography.script_source | nullable_string)
  and (.loadability.lualatex.attempted | type == "boolean")
  and (.loadability.lualatex.loadable | nullable_bool)
  and (.loadability.lualatex.reason | nullable_string)
  and (.loadability.lualatex.runtime_fingerprint | nullable_string)
  and (.loadability.lualatex.probe_input | nullable_string)
  and (
    if .loadability.lualatex.attempted then
      (.loadability.lualatex.loadable != null)
      and (.loadability.lualatex.runtime_fingerprint | nonempty)
      and (.loadability.lualatex.probe_input | nonempty)
    else
      (.loadability.lualatex.loadable == null)
      and (.loadability.lualatex.runtime_fingerprint == null)
      and (.loadability.lualatex.probe_input == null)
    end
  );

{
  schema_version: .metadata.schema_version,
  metadata_validation_ok: metadata_ok,
  checked_fonts: (.fonts | length),
  bad_fonts: [
    .fonts
    | to_entries[]
    | select(.value | font_ok | not)
    | {
        index: .key,
        path: .value.path,
        typography: .value.typography,
        loadability: .value.loadability.lualatex
      }
  ]
}
| . + {all_ok: (.metadata_validation_ok and ((.bad_fonts | length) == 0))}
""".strip(),
        interpretation=(
            "all_ok=true means the schema-1.3 blocks checked here are present "
            "and internally consistent. This does not, by itself, prove that "
            "LuaLaTeX probing semantically succeeded for every font."
        ),
    ),
    QuerySpec(
        name="loadability-summary",
        summary="Summarize whether persisted LuaLaTeX loadability ran.",
        query=r"""
{
  inventory_attempted: .metadata.validation.lualatex.attempted,
  fonts_attempted: ([.fonts[].loadability.lualatex.attempted] | map(select(. == true)) | length),
  fonts_loadable_true: ([.fonts[].loadability.lualatex.loadable] | map(select(. == true)) | length),
  fonts_loadable_false: ([.fonts[].loadability.lualatex.loadable] | map(select(. == false)) | length),
  fonts_loadable_null: ([.fonts[].loadability.lualatex.loadable] | map(select(. == null)) | length)
}
""".strip(),
        interpretation=(
            "inventory_attempted=true means inventory-level probing ran. "
            "fonts_loadable_null>0 means some entries do not have a definitive "
            "persisted loadability result."
        ),
    ),
    QuerySpec(
        name="unresolved-loadability",
        summary="List fonts whose persisted loadability result is still null.",
        query=r"""
.fonts
| to_entries
| map(select(.value.loadability.lualatex.loadable == null))
| map({
    index: .key,
    path: .value.path,
    family: .value.family,
    subfamily: .value.subfamily,
    attempted: .value.loadability.lualatex.attempted,
    loadable: .value.loadability.lualatex.loadable,
    reason: .value.loadability.lualatex.reason,
    probe_input: .value.loadability.lualatex.probe_input,
    specimen_text: .value.typography.specimen_text
  })
""".strip(),
        interpretation=(
            "Rows returned here are inventory entries without a definitive "
            "persisted LuaLaTeX result. Check file format, path existence, and "
            "candidate eligibility before treating them as failures."
        ),
    ),
    QuerySpec(
        name="fontfile-specimens",
        summary="List fonts whose final specimen came from internal font sample text.",
        query=r"""
.fonts
| to_entries
| map(select(.value.typography.specimen_strategy == "internal"))
| map({
    index: .key,
    path: .value.path,
    family: .value.family,
    subfamily: .value.subfamily,
    specimen_text: .value.typography.specimen_text,
    specimen_glyph_count: .value.typography.specimen_glyph_count,
    sample_text: .value.typography.sample_text.text,
    specimen_strategy: .value.typography.specimen_strategy,
    specimen_rejection_reason: .value.typography.specimen_rejection_reason
  })
""".strip(),
        interpretation=(
            'This query treats "coming from the fontfile" as '
            '`typography.specimen_strategy == "internal"`: the final specimen '
            "was selected from the font's embedded sample text rather than "
            "from script or cmap fallback."
        ),
    ),
    QuerySpec(
        name="embedded-sample-text",
        summary="List fonts whose raw inventory entry contains non-empty embedded sample text.",
        query=r"""
.fonts
| to_entries
| map(select((.value.typography.sample_text.text // "") != ""))
| map({
    index: .key,
    path: .value.path,
    family: .value.family,
    subfamily: .value.subfamily,
    sample_text: .value.typography.sample_text.text,
    specimen_strategy: .value.typography.specimen_strategy
  })
""".strip(),
        interpretation=(
            "Rows returned here have non-empty `typography.sample_text.text`, "
            "which means the raw inventory entry preserved embedded sample text "
            "extracted from the font file. In raw `dump-fonts` output this is "
            "independent from final specimen selection, so "
            "`specimen_strategy` may still be `deferred`."
        ),
    ),
)

QUERY_BY_NAME = {spec.name: spec for spec in QUERY_SPECS}


def fail(message: str, *, exit_code: int = 1) -> None:
    """
    Print an error message and terminate.

    Parameters
    ----------
    message : str
        Human-readable failure message written to standard error.
    exit_code : int, optional
        Process exit code used when raising ``SystemExit``.

    Returns
    -------
    None

    Raises
    ------
    SystemExit
        Always raised with the requested exit code.
    """
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(exit_code)


def build_parser() -> argparse.ArgumentParser:
    """
    Construct the command-line parser for the query helper.

    Parameters
    ----------
    None

    Returns
    -------
    argparse.ArgumentParser
        Configured top-level parser with `list`, `show`, and `run`
        subcommands.
    """
    parser = argparse.ArgumentParser(
        prog="inventory-jq-queries",
        description="Saved jq queries for inspecting Fontshow inventory JSON.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("list", help="List available saved queries")

    show_parser = subparsers.add_parser(
        "show",
        help="Print a saved jq query and its interpretation notes",
    )
    show_parser.add_argument(
        "query_name",
        choices=sorted(QUERY_BY_NAME),
        help="Saved query to display",
    )

    run_parser = subparsers.add_parser(
        "run",
        help="Execute a saved jq query against an inventory file",
    )
    run_parser.add_argument(
        "query_name",
        choices=sorted(QUERY_BY_NAME),
        help="Saved query to execute",
    )
    run_parser.add_argument(
        "inventory_path",
        type=Path,
        help="Inventory JSON file to inspect",
    )
    return parser


def render_query_listing() -> str:
    """
    Render the stable human-readable query catalog.

    Parameters
    ----------
    None

    Returns
    -------
    str
        Multi-line listing of query names and summaries.
    """
    lines = ["Available queries:"]
    for spec in QUERY_SPECS:
        lines.append(f"- {spec.name}: {spec.summary}")
    return "\n".join(lines)


def render_query_details(spec: QuerySpec) -> str:
    """
    Render one query with its filter text and interpretation notes.

    Parameters
    ----------
    spec : QuerySpec
        Saved query specification to display.

    Returns
    -------
    str
        Multi-line help text containing the summary, `jq` program, and
        interpretation guidance.
    """
    return "\n".join(
        [
            f"Query: {spec.name}",
            f"Summary: {spec.summary}",
            "",
            "jq program:",
            spec.query,
            "",
            "Interpretation:",
            spec.interpretation,
        ]
    )


def run_saved_query(spec: QuerySpec, inventory_path: Path) -> int:
    """
    Execute one saved `jq` program against an inventory file.

    Parameters
    ----------
    spec : QuerySpec
        Saved query specification to execute.
    inventory_path : pathlib.Path
        Existing JSON inventory path passed to `jq`.

    Returns
    -------
    int
        Process exit status returned by the `jq` subprocess.

    Raises
    ------
    SystemExit
        Raised when `jq` is unavailable or the inventory path does not
        exist.
    """
    if shutil.which("jq") is None:
        fail("jq is not installed or not available in PATH.")
    if not inventory_path.exists():
        fail(f"Inventory file not found: {inventory_path}")
    if not inventory_path.is_file():
        fail(f"Inventory path is not a file: {inventory_path}")

    print(f"# Running query: {spec.name}")
    print(f"# Summary: {spec.summary}")
    print(f"# Inventory: {inventory_path}")
    print("#")
    print("# Interpretation:")
    for line in spec.interpretation.splitlines():
        print(f"# {line}")

    completed = subprocess.run(
        ["jq", spec.query, str(inventory_path)],  # noqa: S607
        check=False,
    )
    return int(completed.returncode)


def main(argv: list[str] | None = None) -> int:
    """
    Dispatch the saved-query helper command-line interface.

    Parameters
    ----------
    argv : list[str] | None, optional
        Command-line arguments to parse. When ``None``, arguments are
        read from ``sys.argv``.

    Returns
    -------
    int
        Process-style exit status code.
    """
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "list":
        print(render_query_listing())
        return 0

    spec = QUERY_BY_NAME[args.query_name]
    if args.command == "show":
        print(render_query_details(spec))
        return 0

    if args.command == "run":
        return run_saved_query(spec, args.inventory_path)

    fail(f"Unhandled command: {args.command}", exit_code=2)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
